[tool.black]
line-length = 88
target_version = ['py37', 'py38', 'py39']
experimental_string_processing = true
exclude = '''
/(
  | \.git
  | __pycache__
  | dist
  | doc/_build
  | doc/auto_examples
  | build
  | \.mypy_cache
)/
'''
